<?php

namespace Database\Seeders;

use App\Models\Exercise;
use Illuminate\Database\Seeder;

class ExerciseSeeder extends Seeder
{
    public function run(): void
    {
        $exercises = [
            [
                'id' => 1,
                'name' => 'Pec Fly',
                'slug' => 'pec-fly',
                'type' => 'strength',
                'description' => 'Isolation exercise aimed at training the pectoralis major muscle',
                'image_path' => 'exercises/dkyYupNTBQPUptAZs83jwCokBN2sQoJPYFhxLJHi.png',
            ],
            [
                'id' => 2,
                'name' => 'Rear Delt',
                'slug' => 'rear-delt',
                'type' => 'strength',
                'description' => 'Training the back of the shoulders',
                'image_path' => 'exercises/dkyYupNTBQPUptAZs83jwCokBN2sQoJPYFhxLJHi.png',
            ],
            [
                'id' => 3,
                'name' => 'Seated Row',
                'slug' => 'seated-row',
                'type' => 'strength',
                'description' => 'A top exercise for the largest back muscles',
                'image_path' => 'exercises/g096462TBG9u30iYvGu086xoQ1BbpNTMfVcQjdhg.png',
            ],
            [
                'id' => 4,
                'name' => 'Pullover',
                'slug' => 'pullover',
                'type' => 'strength',
                'description' => 'A top exercise for the chest muscles',
                'image_path' => null,
            ],
            [
                'id' => 5,
                'name' => 'Shoulder Press',
                'slug' => 'shoulder-press',
                'type' => 'strength',
                'description' => 'Aimed at strengthening the shoulder muscles',
                'image_path' => 'exercises/VF6PpBjzriEkIxZ9Lc2Mt9iFzQYgUF7RGxRHfAak.png',
            ],
            [
                'id' => 6,
                'name' => 'Chest Press',
                'slug' => 'chest-press',
                'type' => 'strength',
                'description' => 'Aimed at strengthening the pectoralis major muscles (pectoralis major), triceps and front shoulders',
                'image_path' => 'exercises/MrSUp0G5w3PVqlIGRJ6EjPTSED5ckducsXqG6JCF.png',
            ],
            [
                'id' => 7,
                'name' => 'Deltoid Raise',
                'slug' => 'deltoid-raise',
                'type' => 'strength',
                'description' => 'Excellent exercise to train the back of the shoulders, the upper back muscle and the neck',
                'image_path' => 'exercises/eA898v3vN6iH37Hshh0I74qgRk8xG6HkYFvXNJFm.png',
            ],
            [
                'id' => 8,
                'name' => 'Back Extension',
                'slug' => 'back-extension',
                'type' => 'strength',
                'description' => '<p>De back extension machine (ook wel hyperextensie bank genoemd) is een effectief fitnesstoestel om de onderrug, bilspieren en hamstrings te versterken. Er zijn verschillende modellen beschikbaar, variërend van compacte bankjes voor thuis tot zware, verstelbare toestellen voor professioneel gebruik</p><p>Aandachtspunten bij Gebruik&nbsp;</p><ul><li><p>Instelling: Zorg dat het heupkussen net onder je heupplooi zit, zodat je vrij kunt buigen zonder dat je bekken geblokkeerd wordt.</p></li><li><p>Focus: Je kunt de oefening aanpassen voor verschillende spiergroepen:</p><ul><li><p>Onderrug: Houd je rug neutraal en kijk recht vooruit.</p></li></ul><ul><li><p>Bilspieren: Draai je voeten licht naar buiten, trek je kin in en maak je bovenrug iets boller om de focus naar je billen te verplaatsen.</p></li></ul></li><li><p>Veiligheid: Vermijd het \"overstrekken\" (te ver naar achteren buigen) van de rug aan de bovenkant van de beweging, omdat dit onnodige druk op de wervelkolom legt.</p></li></ul>',
                'image_path' => 'exercises/vyYjaA7Q5OeEM66v2S0xwRe7SZONamii0rWzNmOz.png',
            ],
            [
                'id' => 9,
                'name' => 'AB Crush',
                'slug' => 'ab-crush',
                'type' => 'strength',
                'description' => null,
                'image_path' => null,
            ],
            [
                'id' => 10,
                'name' => 'Triceps Press',
                'slug' => 'triceps-press',
                'type' => 'strength',
                'description' => 'An isolation exercise for the triceps (the large muscle group at the back of your upper arm)',
                'image_path' => null,
            ],
            [
                'id' => 11,
                'name' => 'Bilateral Arm Curl',
                'slug' => 'bilateral-arm-curl',
                'type' => 'strength',
                'description' => 'Strength exercise in which both arms simultaneously (bilaterally) train the biceps',
                'image_path' => null,
            ],
            [
                'id' => 12,
                'name' => 'Biceps Curl',
                'slug' => 'biceps-curl',
                'type' => 'strength',
                'description' => 'Exercise aimed at strengthening and enlarging the biceps',
                'image_path' => null,
            ],
            [
                'id' => 13,
                'name' => 'Leg Press',
                'slug' => 'leg-press',
                'type' => 'strength',
                'description' => 'Training for your quads, hamstrings and calves',
                'image_path' => 'exercises/mkoo1W2QXtiVcsCBOlptjmwzRTZi2JZXGrITk3Xu.png',
            ],
            [
                'id' => 14,
                'name' => 'Seated Leg Curl',
                'slug' => 'seated-leg-curl',
                'type' => 'strength',
                'description' => 'The leg curl is an effective isolation exercise for training the hamstrings',
                'image_path' => 'exercises/Pu8d0bOOA9UlU5iRxfLVXSMF5hCIJpQFMWWR7GYd.png',
            ],
            [
                'id' => 15,
                'name' => 'Leg Extension',
                'slug' => 'leg-extension',
                'type' => 'strength',
                'description' => 'The leg extension is specifically aimed at training the quadriceps (front of the thighs)',
                'image_path' => 'exercises/r0b4adwIpGelwoW9drO5qxjq2T2snpUyhV0FnjHz.png',
            ],
            [
                'id' => 16,
                'name' => 'Abduction',
                'slug' => 'abduction',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/Lb6fCXmy2xUqSbueuXxTW3BcOQocH4bswYLnwicC.png',
            ],
            [
                'id' => 17,
                'name' => 'Adduction',
                'slug' => 'adduction',
                'type' => 'strength',
                'description' => '<p>De adduction machine (adductiemachine) is een fitnessapparaat dat specifiek bedoeld is voor het isoleren en versterken van de adductoren, oftewel de spieren aan de binnenkant van je dijbeen. Door je benen tegen weerstand in naar het midden van je lichaam te duwen, train je spiergroepen zoals de adductor magnus, longus en de gracilis.&nbsp;</p><p>Hoe gebruik je de machine?&nbsp;</p><ul><li><p>Voor een effectieve en veilige training volg je deze stappen:&nbsp;</p></li><li><p>Instelling: Stel de rugleuning en de wijdte van de kniekussens zo in dat je rechtop zit en een lichte rek voelt in je liezen wanneer de kussens in de startpositie staan.</p></li><li><p>Houding: Houd je rug recht tegen de leuning en pak de handvatten aan de zijkant vast voor stabiliteit.</p></li><li><p>Beweging: Adem uit terwijl je je knieën krachtig naar elkaar toe duwt. Houd deze positie kort vast (1 seconde) om de contractie te maximaliseren.</p></li><li><p>Terugkeer: Breng de kussens gecontroleerd en langzaam weer naar buiten naar de startpositie, zonder dat de gewichtstapel volledig neerkomt, om de spanning op de spieren te behouden.&nbsp;</p></li></ul><p>Belangrijkste voordelen&nbsp;</p><ul><li><p>Heupstabiliteit: Sterke adductoren verbeteren de stabiliteit van het bekken en de heupen, wat essentieel is voor dagelijkse bewegingen en zware lifts zoals squats.</p></li><li><p>Blessurepreventie: Het versterken van deze vaak verwaarloosde spieren kan het risico op liesblessures verminderen en helpt bij de uitlijning van de knieën.</p></li><li><p>Sportspecifiek: Belangrijk voor sporten met snelle zijwaartse bewegingen, zoals voetbal, tennis en schaatsen.&nbsp;</p></li></ul>',
                'image_path' => 'exercises/Lb6fCXmy2xUqSbueuXxTW3BcOQocH4bswYLnwicC.png',
            ],
            [
                'id' => 18,
                'name' => 'Low Row',
                'slug' => 'low-row',
                'type' => 'strength',
                'description' => '<p>De low row machine is een van de meest effectieve fitnessapparaten voor het trainen van de rugspieren. Het bootst de beweging van het roeien na en wordt vooral gebruikt om de breedte en dikte van de rug op te bouwen.&nbsp;</p><p><em><span style=\"font-weight: bold;\"><u>Welke spieren train je?&nbsp;</u></span></em></p><p>Het apparaat richt zich primair op de grote rugspieren, maar activeert ook verschillende ondersteunende spiergroepen:&nbsp;</p><ul><li><p>Latissimus Dorsi (Lats): Voor de bekende \"V-vorm\" van de rug.</p></li><li><p>Rhomboids &amp; Traps: Belangrijk voor een goede houding en het samentrekken van de schouderbladen.</p></li><li><p>Achterste schouderkoppen (Rear Delts): Helpen bij het naar achteren trekken van de armen.</p></li><li><p>Biceps &amp; Onderarmen: Worden gebruikt als ondersteunende spieren tijdens het trekken.&nbsp;</p></li></ul><p><em><span style=\"font-weight: bold;\"><u>Correcte uitvoering en techniek&nbsp;</u></span></em></p><p>Voor een optimaal resultaat en om blessures te voorkomen, is de juiste vorm essentieel:&nbsp;</p><ul><li><p>Instellen: Stel de zitting of borststeun zo in dat je de handvatten met licht gebogen armen kunt vastpakken terwijl je rug recht blijft.</p></li><li><p>Houding: Zit rechtop met je borst naar voren en schouders laag. Houd je voeten stevig tegen de voetsteunen.</p></li><li><p>De Trek: Trek de handvatten naar je onderste ribben of navel. Focus op het naar achteren drijven van je ellebogen in plaats van alleen met je handen te trekken.</p></li><li><p>Squeeze: Knijp je schouderbladen aan het eind van de beweging 1-2 seconden krachtig samen.</p></li><li><p>Teruggang: Laat het gewicht gecontroleerd terugzakken zonder je rug te bollen of momentum te gebruiken.</p></li></ul>',
                'image_path' => null,
            ],
            [
                'id' => 19,
                'name' => 'High Row',
                'slug' => 'high-row',
                'type' => 'strength',
                'description' => 'Aimed at strengthening the upper back and shoulders',
                'image_path' => null,
            ],
            [
                'id' => 20,
                'name' => 'Lat Pull Down',
                'slug' => 'lat-pull-down',
                'type' => 'strength',
                'description' => 'focused on the broad back muscle',
                'image_path' => null,
            ],
            [
                'id' => 21,
                'name' => 'Lunge',
                'slug' => 'lunge',
                'type' => 'strength',
                'description' => 'Effective, unilateral lower body strength exercise that works the quadriceps, hamstrings, glutes and core',
                'image_path' => null,
            ],
            [
                'id' => 22,
                'name' => 'Torso Twist',
                'slug' => 'torso-twist',
                'type' => 'strength',
                'description' => 'Exercise that primarily focuses on the obliques and core muscles',
                'image_path' => null,
            ],
            [
                'id' => 23,
                'name' => 'Squat',
                'slug' => 'squat',
                'type' => 'strength',
                'description' => 'Squats mainly train the large muscle groups in the lower body',
                'image_path' => null,
            ],
            [
                'id' => 24,
                'name' => 'Push Press',
                'slug' => 'push-press',
                'type' => 'strength',
                'description' => 'Exercise that primarily trains the shoulders, triceps and upper chest muscles',
                'image_path' => null,
            ],
            [
                'id' => 25,
                'name' => 'Push Down',
                'slug' => 'push-down',
                'type' => 'strength',
                'description' => 'An exercise that primarily focuses on the triceps',
                'image_path' => null,
            ],
            [
                'id' => 26,
                'name' => 'Hip Glute Press',
                'slug' => 'hip-glute-press',
                'type' => 'strength',
                'description' => 'Exercise aimed at strengthening and shaping the gluteal muscles',
                'image_path' => null,
            ],
            [
                'id' => 27,
                'name' => 'Glute Drive',
                'slug' => 'glute-drive',
                'type' => 'strength',
                'description' => 'For building strength and mass in the buttocks and hamstrings',
                'image_path' => null,
            ],
            [
                'id' => 28,
                'name' => 'Stairmaster',
                'slug' => 'stairmaster',
                'type' => 'cardio',
                'description' => 'Simulates climbing a never-ending flight of stairs',
                'image_path' => null,
            ],
            [
                'id' => 29,
                'name' => 'Indoor rowing',
                'slug' => 'indoor-rowing',
                'type' => 'cardio',
                'description' => 'Simulates the motion of rowing a boat on water',
                'image_path' => null,
            ],
            [
                'id' => 30,
                'name' => 'Treadmill',
                'slug' => 'treadmill',
                'type' => 'cardio',
                'description' => 'Running or walking indoor on the treadmill',
                'image_path' => null,
            ],
            [
                'id' => 31,
                'name' => 'Cross trainer',
                'slug' => 'cross-trainer',
                'type' => 'cardio',
                'description' => 'Trains your entire body, burns calories and strengthens muscles',
                'image_path' => null,
            ],
            [
                'id' => 32,
                'name' => 'Hometrainer',
                'slug' => 'hometrainer',
                'type' => 'cardio',
                'description' => 'Cycling movements to improve physical fitness',
                'image_path' => null,
            ],
            [
                'id' => 33,
                'name' => 'HIIT Bike',
                'slug' => 'hiit-bike',
                'type' => 'cardio',
                'description' => 'Exercise bike that is specially designed for High-Intensity Interval Training',
                'image_path' => null,
            ],
            [
                'id' => 34,
                'name' => 'Seated palms up wrist curl',
                'slug' => 'seated-palms-up-wrist-curl',
                'type' => 'strength',
                'description' => null,
                'image_path' => null,
            ],
        ];

        foreach ($exercises as $exercise) {
            Exercise::updateOrCreate(['id' => $exercise['id']], $exercise);
        }
    }
}
