<?php

namespace Database\Seeders;

use App\Models\Exercise;
use Illuminate\Database\Seeder;

class ExerciseSeeder extends Seeder
{
    public function run(): void
    {
        $exercises = [
            [
                'id' => 1,
                'name' => 'Pec Fly Machine',
                'slug' => 'pec-fly-machine',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/pec-fly-machine.jpg',
            ],
            [
                'id' => 2,
                'name' => 'Rear Delt Machine',
                'slug' => 'rear-delt-machine',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/rear-delt-machine.jpg',
            ],
            [
                'id' => 3,
                'name' => 'Seated Row',
                'slug' => 'seated-row',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/seated-row.jpg',
            ],
            [
                'id' => 4,
                'name' => 'Pullover Machine',
                'slug' => 'pullover-machine',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/pullover-machine.jpg',
                //                    core, shoulders, high-back, upper-arms
            ],
            [
                'id' => 5,
                'name' => 'Shoulder Press',
                'slug' => 'shoulder-press',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/shoulder-press.jpg',
            ],
            [
                'id' => 6,
                'name' => 'Chest Press Machine',
                'slug' => 'chest-press-machine',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/chest-press-machine.jpg',
            ],
            [
                'id' => 7,
                'name' => 'Deltoid Raise',
                'slug' => 'deltoid-raise',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/deltoid-raise.jpg',
            ],
            [
                'id' => 8,
                'name' => 'Back Extension Machine',
                'slug' => 'back-extension-machine',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/back-extension-machine.jpg',
            ],
            [
                'id' => 9,
                'name' => 'AB Crush Machine',
                'slug' => 'ab-crush-machine',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/ab-crush-machine.jpg',
            ],
            [
                'id' => 10,
                'name' => 'Seated Triceps Press',
                'slug' => 'seated-triceps-press',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/seated-triceps-press.jpg',
                //                upper - arms,
            ],
            [
                'id' => 11,
                'name' => 'Bilateral Arm Curl Machine',
                'slug' => 'bilateral-arm-curl-machine',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/bilateral-arm-curl-machine.jpg',
            ],
            [
                'id' => 12,
                'name' => 'Biceps Curl (Cable Station)',
                'slug' => 'biceps-curl-cable-station',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/biceps-curl-cable-station.jpg',
            ],
            [
                'id' => 13,
                'name' => 'Leg Press Machine',
                'slug' => 'leg-press-machine',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/leg-press-machine.jpg',
            ],
            [
                'id' => 14,
                'name' => 'Seated Leg Curl',
                'slug' => 'seated-leg-curl',
                'type' => 'strength',
                'description' => 'The leg curl is an effective isolation exercise for training the hamstrings',
                'image_path' => 'exercises/seated-leg-curl.jpg',
            ],
            [
                'id' => 15,
                'name' => 'Leg Extension Machine',
                'slug' => 'leg-extension-machine',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/leg-extension-machine.jpg',
            ],
            [
                'id' => 16,
                'name' => 'Abduction',
                'slug' => 'abduction',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/abduction.jpg',
            ],
            [
                'id' => 17,
                'name' => 'Adduction',
                'slug' => 'adduction',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/adduction.jpg',
            ],
            [
                'id' => 18,
                'name' => 'Low Row V Grip (Cable Station)',
                'slug' => 'low-row-v-grip',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/low-row-v-grip.jpg',
            ],
            [
                'id' => 19,
                'name' => 'High Row Plated',
                'slug' => 'high-row-plated',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/high-row-plated.jpg',
            ],
            [
                'id' => 20,
                'name' => 'Lat Pull Down (Cable Station)',
                'slug' => 'lat-pull-down-cable',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/lat-pull-down-cable.jpg',
                //                    shoulders, high-back, low-back, upper-arms
            ],
            [
                'id' => 21,
                'name' => 'Lunge (Multi Station)',
                'slug' => 'lunge-multi-station',
                'type' => 'strength',
                'description' => null,
                'image_path' => null,
            ],
            [
                'id' => 22,
                'name' => 'Torso Twist (Multi Station)',
                'slug' => 'torso-twist-multi-station',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/torso-twist-multi-station.jpg',
            ],
            [
                'id' => 23,
                'name' => 'Squat (Multi Station)',
                'slug' => 'squat-multi-station',
                'type' => 'strength',
                'description' => null,
                'image_path' => null,
            ],
            [
                'id' => 24,
                'name' => 'Push Press (Multi Station)',
                'slug' => 'push-press-multi-station',
                'type' => 'strength',
                'description' => null,
                'image_path' => null,
            ],
            [
                'id' => 25,
                'name' => 'Push Down (Multi Station)',
                'slug' => 'push-down-multi-station',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/push-down-multi-station.jpg',
            ],
            [
                'id' => 26,
                'name' => 'Hip Glute Press (Multi Station)',
                'slug' => 'hip-glute-press-multi-station',
                'type' => 'strength',
                'description' => null,
                'image_path' => null,
            ],
            [
                'id' => 27,
                'name' => 'Glute Drive Plated',
                'slug' => 'glute-drive-plated',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/glute-drive-plated.jpg',
            ],
            [
                'id' => 28,
                'name' => 'Stair Machine',
                'slug' => 'stair-machine',
                'type' => 'cardio',
                'description' => 'Simulates climbing a never-ending flight of stairs',
                'image_path' => 'exercises/stair-machine.jpg',
            ],
            [
                'id' => 29,
                'name' => 'Rowing',
                'slug' => 'rowing',
                'type' => 'cardio',
                'description' => 'Simulates the motion of rowing a boat on water',
                'image_path' => 'exercises/rowing.jpg',
            ],
            [
                'id' => 30,
                'name' => 'Treadmill',
                'slug' => 'treadmill',
                'type' => 'cardio',
                'description' => 'Running or walking indoor on the treadmill',
                'image_path' => 'exercises/treadmill.jpg',
            ],
            [
                'id' => 31,
                'name' => 'Cross trainer',
                'slug' => 'cross-trainer',
                'type' => 'cardio',
                'description' => 'Trains your entire body, burns calories and strengthens muscles',
                'image_path' => 'exercises/cross-trainer.jpg',
            ],
            [
                'id' => 32,
                'name' => 'Hometrainer',
                'slug' => 'hometrainer',
                'type' => 'cardio',
                'description' => 'Cycling movements to improve physical fitness',
                'image_path' => 'exercises/hometrainer.jpg',
            ],
            [
                'id' => 33,
                'name' => 'HIIT Bike',
                'slug' => 'hiit-bike',
                'type' => 'cardio',
                'description' => 'Exercise bike that is specially designed for High-Intensity Interval Training',
                'image_path' => 'exercises/hiit-bike.jpg',
            ],
            [
                'id' => 34,
                'name' => 'Seated palms up wrist curl',
                'slug' => 'seated-palms-up-wrist-curl',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/seated-palms-up-wrist-curl.jpg',
            ],
            [
                'id' => 35,
                'name' => 'Tilt Seat Calf Plated',
                'slug' => 'tilt-seat-calf-plated',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/tilt-seat-calf-plated.jpg',
                //                    lower-legs, calves
            ],
            [
                'id' => 36,
                'name' => 'Ski',
                'slug' => 'ski',
                'type' => 'cardio',
                'description' => 'Simulates the motion of skiing',
                'image_path' => null,
            ],
            [
                'id' => 37,
                'name' => 'Chest Press (Cable Station)',
                'slug' => 'chest-press-cable-station',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/chest-press-cable-station.jpg',
            ],
            [
                'id' => 38,
                'name' => 'Ab/Adduction (Cable Station)',
                'slug' => 'ab-adduction-cable-station',
                'type' => 'strength',
                'description' => null,
                'image_path' => null,
            ],
            [
                'id' => 39,
                'name' => 'Shoulder Press Plated',
                'slug' => 'shoulder-press-plated',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/shoulder-press-plated.jpg',
            ],
            [
                'id' => 40,
                'name' => 'Leg Press Plated',
                'slug' => 'leg-press-plated',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/leg-press-plated.jpg',
            ],
            [
                'id' => 41,
                'name' => 'Row Plated',
                'slug' => 'row-plated',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/row-plated.jpg',
            ],
            [
                'id' => 42,
                'name' => 'Incline Press Plated',
                'slug' => 'incline-press-plated',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/incline-press-plated.jpg',
            ],
            [
                'id' => 43,
                'name' => 'Hitt Mill',
                'slug' => 'hitt-mill',
                'type' => 'cardio',
                'description' => null,
                'image_path' => null,
            ],
            [
                'id' => 44,
                'name' => 'Pulldown (Multi Station)',
                'slug' => 'pulldown-multi-station',
                'type' => 'strength',
                'description' => null,
                'image_path' => null,
            ],
            [
                'id' => 45,
                'name' => 'Shoulder Press (Multi Station)',
                'slug' => 'shoulder-press-multi-station',
                'type' => 'strength',
                'description' => null,
                'image_path' => null,
            ],
            [
                'id' => 46,
                'name' => 'Biceps Curl (Multi Station)',
                'slug' => 'biceps-curl-multi-station',
                'type' => 'strength',
                'description' => null,
                'image_path' => null,
            ],
            [
                'id' => 47,
                'name' => 'Ab Crunch (Multi Station)',
                'slug' => 'ab-crunch-multi-station',
                'type' => 'strength',
                'description' => null,
                'image_path' => null,
            ],
            [
                'id' => 48,
                'name' => 'Chest Press (Multi Station)',
                'slug' => 'chest-press-multi-station',
                'type' => 'strength',
                'description' => null,
                'image_path' => null,
            ],
            [
                'id' => 49,
                'name' => 'High Row (Multi Station)',
                'slug' => 'high-row-multi-station',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/high-row-multi-station.jpg',
            ],
            [
                'id' => 50,
                'name' => 'Triceps Press (Cable Station)',
                'slug' => 'triceps-press-cable-station',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/triceps-press-cable-station.jpg',
            ],
            [
                'id' => 51,
                'name' => 'Triceps Kickback (Dumbbell)',
                'slug' => 'triceps-kickback-dumbbell',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/triceps-kickback-dumbbell.jpg',
            ],
            [
                'id' => 52,
                'name' => 'Ab Crunch (Cable Station)',
                'slug' => 'ab-crunch-cable-station',
                'type' => 'strength',
                'description' => null,
                'image_path' => 'exercises/ab-crunch-cable-station.jpg',
            ],
            [
                'id' => 53,
                'name' => 'Bench Press (Dumbell)',
                'slug' => 'bench-press-Dumbell',
                'type' => 'strength',
                'description' => null,
                'image_path' => null,
            ],
            [
                'id' => 54,
                'name' => 'Dumbell Row',
                'slug' => 'dumbell-row',
                'type' => 'strength',
                'description' => null,
                'image_path' => null,
            ],
            [
                'id' => 55,
                'name' => 'Hammer Curl (Cable)',
                'slug' => 'hammer-curl-cable',
                'type' => 'strength',
                'description' => null,
                'image_path' => null,
            ],
        ];

        foreach ($exercises as $exercise) {
            Exercise::updateOrCreate(['id' => $exercise['id']], $exercise);
        }
    }
}
